"""
Django settings for uwmroommatefinder project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# This tells the library to ignore the "Scope has changed" warning
os.environ['OAUTHLIB_RELAX_TOKEN_SCOPE'] = '1'

load_dotenv() # Load environment variables from .env file for microsoft auth

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("DJANGO_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'base',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',  # For microsoft auth
    'microsoft_auth',        # FOr microsoft auth
    'corsheaders',       # React to talk to Django backend
    'rest_framework',    # React to talk to Django backend
    'storages',          # Google Cloud Storage (Firebase) file backend
]

SITE_ID = 1 # For microsoft auth

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'uwmroommatefinder.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'microsoft_auth.context_processors.microsoft',
            ],
        },
    },
]

WSGI_APPLICATION = 'uwmroommatefinder.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases
# PostgreSQL — run the DB via Docker Compose: `docker compose up -d db`

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('DB_NAME', 'uwmroommatefinder'),
        'USER': os.getenv('DB_USER', 'postgres'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# For microsoft auth, allows users to log in with their Microsoft account
AUTHENTICATION_BACKENDS = [
    'microsoft_auth.backends.MicrosoftAuthenticationBackend', # Adds Microsoft login
    'django.contrib.auth.backends.ModelBackend', # Keeps normal admin login working
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# MICROSOFT AUTH CONFIGURATION
# The library looks for these exact variable names
MICROSOFT_AUTH_CLIENT_ID = os.getenv("MICROSOFT_APP_ID")
MICROSOFT_AUTH_CLIENT_SECRET = os.getenv("MICROSOFT_APP_SECRET")
MICROSOFT_AUTH_TENANT_ID = "common"  # Use "common" for multi-tenant apps

# Login Type
MICROSOFT_AUTH_LOGIN_TYPE = "ma"  # Microsoft Account (includes Personal & School)

# Domain restriction (The "UWM Only" guard)
# The library uses a validator function for this, not a simple list.
# We will add a validator to check the email domain.
MICROSOFT_AUTH_EXTRA_SCOPES = "user.read"

def validate_uwm_email(user, token=None):
    if not user.email.endswith("@uwm.edu"):
        from django.core.exceptions import PermissionDenied
        raise PermissionDenied("Only UWM email addresses are allowed.")
    
    # Always sync admin status with the ADMIN_EMAILS env var on every login.
    # This means adding OR removing an email from .env takes effect immediately
    # on next login — no manual DB edits needed.
    admin_emails_str = os.getenv("ADMIN_EMAILS", "")
    admin_emails = [email.strip().lower() for email in admin_emails_str.split(",") if email.strip()]
    
    is_admin = user.email.lower() in admin_emails
    if user.is_staff != is_admin or user.is_superuser != is_admin:
        user.is_staff = is_admin
        user.is_superuser = is_admin
        user.save()

# Tell the library to use this validator
MICROSOFT_AUTH_AUTHENTICATE_HOOK = "uwmroommatefinder.settings.validate_uwm_email" 

# Tells Django to trust requests from the React frontend (for development purposes)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
    "http://localhost:3000",
]

CORS_ALLOW_CREDENTIALS = True # Allows cookies to be sent to and from port 8000 and 5173
# which is necessary for authentication to work in development.

# URL to redirect to after successful logout (e.g., the home page or login page)
LOGOUT_REDIRECT_URL = '/'

# Default URL for login, used by login_required decorator
LOGIN_URL = '/accounts/login/'

# URL to redirect to after successful login
LOGIN_REDIRECT_URL = '/'


# ---------------------------------------------------------------------------
# Google Cloud Storage (Firebase Storage) — file / media uploads
# ---------------------------------------------------------------------------
# Docs: https://django-storages.readthedocs.io/en/latest/backends/gcloud.html
#
# Prerequisites:
#   1. pip install -r requirements.txt  (includes django-storages[google] + google-cloud-storage)
#   2. Download a service-account JSON key from Firebase Console →
#      Project Settings → Service Accounts → Generate new private key
#   3. Set GS_CREDENTIALS and GS_BUCKET_NAME in your .env file

DEFAULT_FILE_STORAGE = 'storages.backends.gcloud.GoogleCloudStorage'

GS_BUCKET_NAME = os.getenv('GS_BUCKET_NAME', '')          # e.g. 'uwm-roommate-media'
GS_CREDENTIALS = os.getenv('GS_CREDENTIALS', '')           # abs path to service-account.json

# Public URL prefix for serving stored files
MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/' if GS_BUCKET_NAME else '/media/'

# Cache-Control header for uploaded objects (1 day)
GS_OBJECT_PARAMETERS = {
    'cache_control': 'public, max-age=86400',
}


# ---------------------------------------------------------------------------
# Firebase Admin SDK Initialization
# ---------------------------------------------------------------------------
if GS_CREDENTIALS and os.path.exists(GS_CREDENTIALS):
    import firebase_admin
    from firebase_admin import credentials
    
    # Check if app is already initialized to avoid "app already exists" error
    if not firebase_admin._apps:
        cred = credentials.Certificate(GS_CREDENTIALS)
        firebase_admin.initialize_app(cred)