# Generated by Django 6.0.2 on 2026-02-26 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='programs',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
