# Generated by Django 6.0.2 on 2026-02-26 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_profile_programs'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='dorm_building',
            field=models.CharField(choices=[('C', 'Cambridge Commons'), ('R', 'Riverview'), ('S1', 'Sandburg (N/S/W)'), ('S2', 'Sandburg (E)')], default='C', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='O', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='profile',
            name='room_type',
            field=models.CharField(choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple')], default='S', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='standing',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], default='FR', max_length=2),
        ),
        migrations.AddField(
            model_name='profile',
            name='term',
            field=models.CharField(choices=[('F', 'Fall'), ('S', 'Spring')], default='F', max_length=2),
        ),
    ]
