# Generated by Django 6.0.2 on 2026-03-04 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_group_profile_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_profile_complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='profile',
            name='dorm_building',
            field=models.CharField(blank=True, choices=[('C', 'Cambridge Commons'), ('R', 'Riverview'), ('S1', 'Sandburg (N/S/W)'), ('S2', 'Sandburg (E)')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='room_type',
            field=models.CharField(blank=True, choices=[('S', 'Single'), ('D', 'Double'), ('T', 'Triple')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='standing',
            field=models.CharField(blank=True, choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior')], max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='term',
            field=models.CharField(blank=True, choices=[('F', 'Fall'), ('S', 'Spring')], max_length=2, null=True),
        ),
    ]
