# Generated by Django 6.0.2 on 2026-03-12 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='incoming_requests',
            field=models.ManyToManyField(blank=True, related_name='outgoing_requests', to='base.profile'),
        ),
    ]
