# Generated by Django 6.0.2 on 2026-03-13 00:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_profile_is_profile_complete_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('liked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to='base.group')),
                ('liker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to='base.group')),
            ],
            options={
                'unique_together': {('liker', 'liked')},
            },
        ),
    ]
