# Generated by Django 6.0.2 on 2026-03-19 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_grouplike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='preferences',
        ),
        migrations.AddField(
            model_name='profile',
            name='alcohol_policy',
            field=models.IntegerField(blank=True, choices=[(0, 'Strictly Dry'), (1, 'Occasionally'), (2, 'Comfortable')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='alcohol_policy_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness',
            field=models.IntegerField(blank=True, choices=[(0, 'Very Clean'), (1, 'Moderate'), (2, 'Relaxed')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='cleanliness_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='guest_policy',
            field=models.IntegerField(blank=True, choices=[(0, 'Barely'), (1, 'Occasionally'), (2, 'Frequently')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='guest_policy_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Quiet'), (1, 'Moderate'), (2, 'Lively')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='noise_level_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='shared_belongings',
            field=models.IntegerField(blank=True, choices=[(0, 'Keep Separate'), (1, 'Ask First'), (2, 'Share Everything')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shared_belongings_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_habits',
            field=models.IntegerField(blank=True, choices=[(0, 'Early Bird'), (1, 'Moderate'), (2, 'Night Owl')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='sleep_habits_priority',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_level',
            field=models.IntegerField(blank=True, choices=[(0, 'Introvert'), (1, 'Ambivert'), (2, 'Extrovert')], null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='social_level_priority',
            field=models.BooleanField(default=False),
        ),
    ]
