# Generated by Django 6.0.2 on 2026-04-01 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_profile_incoming_requests'),
        ('base', '0007_remove_profile_preferences_profile_alcohol_policy_and_more'),
    ]

    operations = [
    ]
