# Generated by Django 6.0.2 on 2026-04-02 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_merge_20260401_1318'),
        ('base', '0008_profile_is_active'),
    ]

    operations = [
    ]
