# Generated by Django 6.0.2 on 2026-04-01 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_merge_0008_merge_20260401_1318_0008_profile_is_active'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GroupLike',
        ),
    ]
