# Generated by Django 6.0.2 on 2026-04-16 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_set_site_domain'),
        ('base', '0010_delete_grouplike'),
    ]

    operations = [
    ]
