# Generated by Django 6.0.2 on 2026-04-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_delete_grouplike'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='checklist',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
