# Generated by Django 6.0.2 on 2026-04-16 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_merge_0006_set_site_domain_0010_delete_grouplike'),
        ('base', '0011_profile_checklist'),
    ]

    operations = [
    ]
